### ISSUE TITLE
Settings in the config file will not be updated if the corresponding line doesn't exist

### ISSUE THREAD

**Issue by katarn88** [gort818/openjklauncher#2]
Functions that update config settings ([on_checkbutton_toggled](https://github.com/gort818/openjklauncher/blob/master/openjk#L450), [on_checkbutton2_toggled](https://github.com/gort818/openjklauncher/blob/master/openjk#L467), [on_modlist_changed](https://github.com/gort818/openjklauncher/blob/master/openjk#L484)) will not save the changes if the lines related to the setting do not already exist in the config file.

**Comment by gort818** [comment]
That is what the create_file() function is for.
